name = "imobiliaria-sonho"
main = "index.js" # Este campo é para Workers, mas é bom tê-lo.
compatibility_date = "2025-05-09" # Use a data atual ou uma futura.

[vars]
# Variáveis de ambiente, se precisar
# CHAVE_API = "valor-da-chave"

[[d1_databases]]
binding = "DB"
database_name = "sonho-imobiliario"
database_id = "c608e82d-c2bc-4834-92c6-f452bed1ef88"